name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Upload to S3
        run: aws s3 sync . s3://finger-math

      - name: Create CloudFront Invalidation
        run: |
          distribution_id="E1EV5DWRXMGW95"  # Điều chỉnh với ID của CloudFront Distribution của bạn
          aws cloudfront create-invalidation --distribution-id $distribution_id --paths '/*'
